data/AboutSyncTableInspector.js
data/aboutsync.css
data/components.js
data/index.html

Has a number of improved features listed in the commit message. Works like a drop-in replacement. It probably needs some CSS work though (it looks fine, but I didn't spend much time on the styling).
That said, I gave this some thinking and while this may be an improvement over the one we had before, what we probably want is something that will let us view the differences between two record lists (e.g. the list of remote items, and list of local items). Something like that could be built on top of this but I'm not sure something more custom wouldn't be better. (Although, being able to view just the record list on its own without any of this is probably still valuable).
Just a thought I had while working on the comparison code, since comparing lists of records is much simpler than comparing …

Replace react-inspector's TableInspector with a custom table inspector

---

data/components.js

Had this mostly done in a branch, but had forgotten until I read the part of your email asking for react style feedback.
This fixes all the react warnings that it would log into the console. Nothing too substantial here, most of them were about not providing `key` properties to array elements. 
Admittedly, for some of these cases the better option would be to provide "key" properties instead of using a spread to hide the fact that this is an array from react, but... well, I tried both and this one ended up being much cleaner.

Fix react warnings

---

data/AboutSyncTableInspector.js
data/aboutsync.css

Fixes relating to the email you sent me last night.
We'd crash and be terribly broken if we gave AboutSyncTableInspector an array containing null or undefined. Now we handle this. To distinguish between e.g. an empty object and undefined/null, there's a new (record) column that contains the, err, actual record was passed in for this row.
Also, at least AFAICT we were breaking the rules by having a div in a th element, so I've changed it to a display:block span, and moved it to thead (this doesn't appear to matter, but it seems like it's worth doing).  I don't think this was the cause of the "findComponentRoot" issue, but I also can't 100% rule it out, and since it seems like it could potentially someday be an issue, why not do it now.
I've also tweaked the CSS to handle this last change, …

Fix handling of non-object records in table inspector, and ensure there's no flow content in "th"

---

data/components.js

This is broken for all other validators currently, and causes their panels not to display if you actually have dupes in them.

Fix duplicates view for non-bookmark validators

---

data/components.js

I had this locally while debugging the feature. (Worth noting that it won't show chris's bookmarks' client cycles, since our calls into places to follow the queries only will work if you actually have these as local bookmarks.)

Show detected client cycles in the bookmark validator view

---

data/components.js

Might be jumping the gun ever so slightly here, but since I'm already messing with aboutsync I might as well delete this.
Worth noting that everything should still work without this patch, as we check that we actually got an array inside describeProblemList -- You could even argue that we *shouldn't* land this patch until more users will have the other patch, although since we don't actually care about this error it sounds like it would just confuse people.

Delete wrongParentName from bookmark validator view since that property no longer exists.

---

data/components.js

`compareServerWithClient` becomes an async function in https://bugzilla.mozilla.org/show_bug.cgi?id=1323867.

Support sync and async validation

---

data/aboutsync.css
data/components.js
data/provider.js

Display an error in the collection summary if there are null records, and add the raw records (and their original data pre-decryption and deserialization) to the "Response" tab, since we weren't displaying that data anywhere.
Certainly the raw records are useful, but I'm willing to take out the predecryption/deserialization data if you are not okay with the WBORecord.prototype monkeypatch.
Related to [bug 1356581 on bugzilla](https://bugzil.la/1356581).

Better handling of null records, fixes #26

---

data/provider.js

This has been bothering me forever.

Fix lastModified timestamp display confusing seconds and milliseconds

---

data/provider.js

The Python and Go servers behave differently when fetching records
without a limit: Python assumes "no limit" and returns everything,
while Go uses the default limit (1k). This meant the validator only
fetched a maximum of 1k records when talking to a Go server, and
reported all other records as "server missing".
In mozilla-services/go-syncstorage#166, @rfk suggested using download
batching instead of relying on the absence of a limit.

Use `getBatched` in Firefox 52+

---

data/components.js

When people report devices list inconsistencies, I often ask them to copy the clients collection from about:sync and open the inspector on accounts.mozilla.com to copy the FxA devices list.
With this PR we can have both at the same place :)

Add a FxA Devices tab to the client section

---

bootstrap.js
data/index.html

When doing some of the system addon work I came across pocket's [pages](https://searchfox.org/mozilla-central/source/browser/extensions/pocket/content/AboutPocket.jsm), which don't have in the AboutRedirector.cpp, so I based what it does on that more or less. It also doesn't seem to need an entry in the manifest either (although some documentation I found suggested that restartless addons can't/shouldn't put components there, so maybe this is expected).
I don't know if there are issues with doing it this way, but I haven't noticed any.

Issue #19 - Register an nsIAboutModule for about:sync

---

data/index.html

For whatever reason, `script type="text/javascript;version=1.7"` no longer loads (I think this is due to [bug 1428002](https://bugzil.la/1428002) landing, but that's a wild guess), which includes all the interesting parts of about:sync. We never needed this in the first place, so it's easiest to just take it out.
Without this patch, about:sync is completely broken.

Fix about:sync being broken on nightly due to not loading our scripts.

---

data/aboutsync.css
src/provider.jsx

* For local sync data, the options are "limit history", "anonymize", and "export to file".
* For loading from a URL or file, the options are the URL input and file picker.
This commit groups the options with their matching providers, flattens `ProviderOptions` into `ProviderInfo` at the cost of some duplicated elements, and fixes a small typo that caused de-anonymized exporting to fail.

Fix up data provider options

---

src/CollectionsViewer.jsx

The clients engine is never registered in the engine manager for Reasons, so we need to special case it to allow client records edition to work.

Allow client records edition

---

bootstrap.js
data/config.js
src/CollectionsViewer.jsx

I tested this out on Firefox ESR 52. A few things have changed since 52, which prevented About Sync from working:
* `ChromeUtils.import` was added in [Firefox 59](https://bugzilla.mozilla.org/show_bug.cgi?id=1431057).
* `console` was exposed to `System` in [Firefox 59](https://bugzilla.mozilla.org/show_bug.cgi?id=1425463).
* Global `C*` aliases were added in [Firefox 60](https://bugzilla.mozilla.org/show_bug.cgi?id=767640).
* `fxAccounts.getDevices` was added in [Firefox 55](https://bugzilla.mozilla.org/show_bug.cgi?id=1339861).
I also fixed a harmless, but annoying error that we'd log to the Browser Console if we called `Config.finalize()` before `initialize()`, and tried to remove the config observer before it was added...but I'm happy to drop this commit if it's not necessary.

Compatibility fixes for Waterfox and ESR

---

src/config.jsx

In [bug 1617503](https://bugzilla.mozilla.org/show_bug.cgi?id=1617503#c13), a user was having issues with a wedged Places
connection. I was curious if that was caused by a stuck merge runnable,
so I asked the user to enable trace logging. However, Desktop doesn't
flush log files to disk (via `resetFileLog`) until the sync finishes
or there's an error—see `policies.js` for those cases. This means
log files aren't always helpful for seeing stuck syncs.
We do provide an option for `dump` logging, but that requires
launching Firefox from the command line, which is tricky if you're
not used to doing that, and also includes lots of other warnings and
log output. The Browser Console is much easier to access, and also
gives us live logs. We already have a pref controlling that, and this
patch …

Add an option to enable Browser Console logging

---

data/AboutSyncRedirector.js

This is causing us to fail to register `about:sync` in Firefox 102 and later.

Fix about: registration for bug 1514936

---

ext_bootstrap.js

I previously moved away from a data: URL for registration because it
stopped working, but forgot to update the unregistration.

Fix unregistering of the addon.

---

manifest.json
src/CollectionsViewer.jsx
src/common.jsx
src/main.jsx

While I could have made this work with earlier versions without too much trouble, I also bumped the min-version to 103 because other changes are coming down the line which changes many of the filename in the sync and fxaccounts filenames, which will be a PITA to support for older versions, so I just bit the bullet here.
Feel free to point out better ways to do the react foo.

Fix fallout from bug 1771463 and show errors during initializtion

---

README.md
manifest.json
package.json
src/CollectionsViewer.jsx
src/main.jsx

As we discussed briefly in slack, I think the best thing to do for now is stick with supporting all versions.
I also discovered the version actually used is in `package.json`, which is why we've been on `0.19.0` 🤷 - so I bumped that to `0.20.0` while I'm at it.

Revert requirement for 103 and add work-arounds for 102 and earlier

---

src/CollectionsViewer.jsx
src/bookmarkValidator.js

This fixes the current nightly bug where bookmark_validator.js moved to bookmarkValidator.jsm and into the tps module as part of the ESM refactoring

Moved bookmark validator into the repo

---

manifest.json
src/CollectionsViewer.jsx
src/config.jsx
src/provider.jsx

About Sync is currently broken on nightly (and will be broken on beta soon). We need to use the new IOUtils instead of the now-removed OS.File.
https://github.com/mozilla/gecko-dev/blob/ae292ebba6074601b33fa983dd4e01ce6a1ec4ac/dom/docs/ioutils_migration.md
Has some nice documentation on the migration equivalents. I've almost fixed everything except downing a combined summary since there is no equivalent for `openUnique` or even `open`. Wanted to throw this one up early though.

Update areas using OS.File to the new IOUtils

---

README.md
manifest.json
package.json

Running into issues updating the addon due to `114.0a1` apparently not existing in https://addons.mozilla.org/api/v5/applications/firefox/
which gives the error when uploading the new XPI
Also bump the version just incase so the addon pipeline CI doesn't get confused.

Change strict_min_version to not include 0a1

---

README.md
package-lock.json
src/AboutSyncRecordEditor.jsx

The main problem being fixed here is that if the record editor sees an error, it fails to render it:
```
console.log: "Bad current record" null "{\n  \"bmkUri\": \"https://www.ozbargain.com.au/node/409403\",\n  \"dateAdded\": 1539657026637,\n  \"hasDupe\": true,\n  \"id\": \"--mM58RLNMB3\",\n  \"parentName\": \"OzB | New\",\n  \"parentid\": \"sqx21Cw3SEv9\",\n  \"title\": \"Men's 100% Cotton Jacket $11.98, T-shirt Fr $3.98, 80% Cotton Zipped Fleece $10 & More + $9.99 Shipped @ Sportdirect\",\n  \"type\": \"bookmark\",\n  \"extra\": {\"foo\": \"bar\"},\n}"
console.error: (new TypeError("e.renderErrorMsg is not a function", "chrome://aboutsync/content/build.js", 2))
console.error: "About Sync: Failed to fetch collection" (new TypeError("e.renderErrorMsg is not a function", …
```

Fix record editor error

---

ext_bootstrap.js

We recently removed `Svc.Prefs`, which breaks about:sync

Remove use of the now removed `Svc.Prefs` object

---

manifest.json
package.json

@mozilla-extensions/releng
This change is needed for https://github.com/mozilla-extensions/xpi-manifest/pull/215
In [Bug 1793925](https://bugzilla.mozilla.org/show_bug.cgi?id=1793925), Firefox Desktop started to emit warnings when an extension's version doesn't match the format specified in the [MDN docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version#version_format).
To comply with this format, we need to drop the patch version on the add on pipeline web extensions.
The pipeline will now generate versions as `major.minor.date.time`

Update addon version to major.minor schema

---

src/CollectionsViewer.jsx

This engine isn't shipped in Thunderbird, and failing to import it prevents about:sync from displaying anything in Thunderbird.

Import forms.sys.mjs lazily into CollectionsViewer.jsx

---

ext_bootstrap.js
manifest.json
package-lock.json
src/bookmarkValidator.js
webext/implementation.js

Includes a couple of fixes found by `npm audit` and lists that it's only available for 136 and up.

Update now that all builtin Firefox modules are eslint modules
