mozilla-extensions/aboutsync

data/components.js

Also separates "structural" differences (e.g. parent/child) from other differences, as you mentioned in the email.

Ensure we report all detected problems in bookmark validation

---

data/AboutSyncTableInspector.js
data/aboutsync.css

It was pretty annoying that you could not do this.

Make table columns resizable

---

data/components.js

That is, there's one table for orphans, one table for serverMissing, etc. Not positive this is the direction we want to go in, but it makes the validator's results much more readable when it has several of the same problem.

Coalesce repeated complaints about the same problem into one table

---

data/components.js

Fix structuralDifferences display now that the validator categorizes these separately itself

---

data/components.js

Goes along with the recent patch to [bug 1286915](https://bugzilla.mozilla.org/show_bug.cgi?id=1286915).
Not really asking for merge yet, it needs some cleanup, but if you have my patch above, it does display the validation results and errors (and the full set of installed addons).

Preliminary integration of the addon validator

---

data/components.js

Mainly focused on making the structural differences and differences easier to follow,
Except for the last bit, which is a react warning fix that probably should be a separate patch but isn’t.

Various improvements to bookmark validator panel.

---

data/provider.js

This is untested (not sure how to test) and probably is slightly overengineered and has bugs. But it's a start...

Treat about pages in more detail when anonymizing (fixes #17)

---

README.md

Maybe there is a need to keep both procedures, please comment and I will make the changes.

Update the procedure to install the plugin locally.

---

data/aboutsync.css
data/components.js

As in #24, but with 100% less services-common/async.js

Show syncChangeCounter/syncStatus in client bookmark and add a SQL query runner tab.

---

data/config.js

Admittedly, there's not that strong a need for this, but it's certainly not useless, and I felt compelled to add it. Oh well, at least with this we'd be able to recommend a method of attaching log files in bulk that isn't a pain for us to read later.
It has a progress indicator unlike the zip file downloader, since it doesn't block the UI when running (so you might not know it's working). It also takes long enough to warrant that, IMO (a few seconds). If the zip writer didn't block the UI, I'd have added a progress indicator for it too, but there's no point to doing that.
It probably doesn't replace the python script for us (as I mention in the commit message), but one benefit of it over that one is that if you open the log in sublime, you can [collapse …

Port the python log summary script to JS and include it in aboutsync.

---

data/AboutSyncRecordEditor.js
data/aboutsync.css
data/components.js
data/index.html
data/provider.js

We probably should have had this for a while, if I'm being honest.

Add an editor panel that lets you edit, add, and delete server records.

---

bootstrap.js

See [Bug 1439777](https://bugzilla.mozilla.org/show_bug.cgi?id=1439777) for context.
This takes on a double approach:
- From now on, Firefox will send `success-log-written`/`error-log-written` alongside with `weave:service:reset-file-log` in `data`. This allows us to listen to `reset-file-log` directly instead of `weave:ui:*` which is going away.
- For old versions of Firefox not sending that `data` field, we fall back to `isLastLogFileError()`.

Listen to weave:service:reset-file-log instead of weave:ui:*

---

bootstrap.js
data/aboutsync.css
data/config.js
src/config.jsx
src/main.jsx
src/panel.jsx

There are some big changes here - hopefully most of them are somewhat obvious. There's a good chance some changes are necessary, but I think it's in good enough shape to get some feedback. @kitcambridge and @thomcc, WDYT?

Config revamp

---

src/PlacesSqlView.jsx

These got merged in https://bugzilla.mozilla.org/show_bug.cgi?id=1458910.

`nsPIPlacesDatabase` is now part of `nsINavHistoryService`

---

data/AboutSyncRedirector.js
data/aboutsync.css
data/config.js
src/CollectionsViewer.jsx
src/EngineActions.jsx
src/config.jsx

generateQI is now in ChromeUtils - fixes #61

---

manifest.json
src/AccountInfo.jsx

Since bug 1574052 has landed, there's no separate profile call anymore.

Remove separate profile fetch call

---

src/CollectionsViewer.jsx

`fxAccounts.getDeviceList()` was replaced with `fxAccounts.device.recentDeviceList` and `refreshDeviceList()` in 71.

Use new FxA APIs to fetch device lists.

---

chrome.manifest
ext_bootstrap.js

Use the technique Thom found to register chrome URLs.

---

package-lock.json
package.json
webpack.config.js

This is turning into a yak shaving festival - from "native" windows it seems like this works, but from wsl it does not - wsl seems like it is way behind in npm versions and I'm struggling to update it.
@skhamis does this look sane to you and does it actually work for you? Any ideas/advice?

Attempt to update node packages

---

README.md

Given the recent massive thread on #addons-pipeline, I believe this is the current process we need to follow. @wagnerand, does this look right?

Update the release process docs

---

README.md

Hey @wagnerand, I wasn't aware of this extra step in getting a release-signed XPI, so thought I should update the docs!

Update README about the process for getting a signed XPI

---

data/AboutSyncRedirector.js
data/config.js
ext_bootstrap.js
src/PlacesSqlView.jsx
src/config.jsx
src/main.jsx
src/provider.jsx

Seems to work OK for me and I think I followed [the instructions](https://groups.google.com/a/mozilla.org/g/firefox-dev/c/wagVSAZ6PME) correctly

Prepare for the removal of Services.jsm

---

package.json

Might as well get the ducks in a row so that I can start the release process once #93 lands.

Bump version preparing for a new release

---

package-lock.json
package.json
src/main.jsx
webpack.config.js

Was looking into some UI components and figured I split this out into its own PR instead of bundling with some UI changes i'm making.

Update react to v18, adjust webpack to allow easier css re-loading

---

package.json

I guess we need a new release!

Bump version to 0.22.0

---

data/config.js
package-lock.json
package.json
src/AboutSyncRecordEditor.jsx
src/AccountInfo.jsx
src/CollectionsViewer.jsx
src/EngineActions.jsx
src/common.jsx
src/config.jsx
src/main.jsx
src/provider.jsx

There are a number of tweaks here, so this is probably best reviewed per commit - I figured it's not really worth a PR for each fairly small patch.
In particular though, it's now impossible to get each log file in a .zip - instead the "combined" log file is the only thing you can get (either as text or as a .zip) - mainly because it's a PITA to deal with the old .zip file when you receive it. LMK what you think.

A number of misc improvements

---

package.json

Might as well release a version with those other tweaks...

Bump version to 0.23.0

---

data/config.js
ext_bootstrap.js

about-sync was broken by https://bugzilla.mozilla.org/show_bug.cgi?id=1872673

Update use of Console.sys.mjs to reflect recent m-c changes

---

data/aboutsync.css
src/CollectionsViewer.jsx
src/EngineActions.jsx
src/WebExtStorage.jsx

This tab lets you get and set via the "browser.storage.sync" API.

Add a "storage.sync" tab to the extension-storage collection.
